### ISSUE TITLE
Canceled/No Show Button

### ISSUE THREAD

**Issue by amandanafe** [BergelsonLab/RPAD#17]
**Describe the bug**

Canceled/No Show Button still works the same way as before it is just relabeled. Canceled and No show should be treated differently. 

**To Reproduce**
1. Go into scheduled appointments. 
2. Select the pencil.
3. Select No Show/Cancel 
Currently the only option is to call them because they were a no show. It will then tag them as complete to the study (if you chose answer- no longer interested) with the note "No show for appointment (apt date). 

When Selecting No Show/Cancel what it should do:
1. Give you a button for No Show and a button for Cancel 
2. No Show button should then do exactly as it is doing now (and stated above)
3. Cancel button should give you the option to:
-"Cancel via email" button or "Cancel via phone" button
- no matter what they chose for the method of cancel we want to know if they are still interested in rescheduling the appointment.. Buttons should say "Potentially interested in rescheduling" and "Not interested in rescheduling" 
3a. Potentially interested in rescheduling button should then take you back to the main page to determine eligibility and then to later select a callback date. 
3b. Not interested in rescheduling can then tag them as complete for the study and make a note that says "Canceled appointment for (apt date) and not interested in rescheduling. 

This is a general issue across studies, but it can be clearly seen in JARSC.
please note the notes in the study section can be manually changed later. 
(please email me if you'd like a specific name for an example)

**Comment by ebergelson** [comment]
hi @amandanafe, instead of opening a new issue, if you believe this is the same as an old issue you should reopen the old issue (which is under closed now). i believe you're referring to this one: https://github.com/BergelsonLab/RPAD/issues/11 
and i think the button rename was the solution we'd agreed on. 

if you could delete this issue and reopen that one if there is still a problem that would be best
